import "./globals.css";
import Layout from "@/components/layout/Layout";

export const metadata = {
  title: "NextJS Course",
  description: "Generated by create next app",
};


export default function RootLayout({ Component, children }) {
  return (
    <html lang="en">
      <body >
        <Layout>{children} </Layout>
      </body>
    </html>
  );
}
